//Just the bare minimum to create a new work order
//No work order ID since it is generated by the backend
export interface NewWorkOrder {
  date_created: Date; //This should be on the frontend to ensure it doesn't reflect server time
  meter_id: number;
  title: string;
}
